const CATS=[["iverica","Иверка"],["medijapan","Медијапан"],["ploca","Работна плоча"],["kant","Кант"],["klizac","Клизач"],["sarka","Шарка"],["racka","Рачка"],["sitno","Ситен материјал"],["trud","Труд"],["montaza","Монтажа"],["prevoz","Превоз"],["ostanato","Останато"]];
const UNITS=[["tabla","табла"],["m2","м²"],["m","м"],["kom","ком"],["komplet","комплет"],["hr","час"]];
const DEFAULT_CATALOG=[{code:"D123",name:"Иверка даб 18мм",cat:"iverica",unit:"tabla",price:55},{code:"PVC2",name:"PVC кант 2мм",cat:"kant",unit:"m",price:0.85},{code:"KL500SC",name:"Клизач 500 soft-close",cat:"klizac",unit:"kom",price:9.8},{code:"SHSC",name:"Клапшарка soft-close",cat:"sarka",unit:"kom",price:1.9},{code:"MONT",name:"Монтажа",cat:"montaza",unit:"komplet",price:60},{code:"PREVOZ",name:"Превоз",cat:"prevoz",unit:"komplet",price:25},{code:"VNT",name:"Ситен материјал",cat:"sitno",unit:"komplet",price:12},{code:"KROJ",name:"Кроење / табла",cat:"trud",unit:"tabla",price:8}];
const DEFAULT_SETTINGS={wastePct:12,vatPct:18,marginPct:20,currency:"EUR",defaultTransport:25,defaultInstall:60};
const $=id=>document.getElementById(id);
const uid=()=>Math.random().toString(36).slice(2,9);
function loadState(){try{const r=localStorage.getItem("mebel-kalkulator-v1");if(r)return JSON.parse(r);}catch(e){}const id=uid();return{settings:{...DEFAULT_SETTINGS},catalog:DEFAULT_CATALOG.map(x=>({...x,id:uid()})),projects:[{id,name:"Понуда 1",clientName:"",clientPhone:"",clientCity:"",leadTime:21,items:[]}],currentId:id};}
let state=loadState(),searchSelected=null,modalMode=null,ocrRows=[],ocrFiles=[];
const save=()=>localStorage.setItem("mebel-kalkulator-v1",JSON.stringify(state));
const currentProject=()=>state.projects.find(p=>p.id===state.currentId)||state.projects[0];
const catLabel=v=>(CATS.find(c=>c[0]===v)||[v,v])[1];
const unitLabel=v=>(UNITS.find(c=>c[0]===v)||[v,v])[1];
function fillSelect(el,pairs,value){el.innerHTML=pairs.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");if(value)el.value=value;}
const money=n=>`${(Number(n)||0).toFixed(2)} ${state.settings.currency}`;
const escapeAttr=s=>String(s||"").replaceAll('"','"');
function findByCode(code){const c=String(code||"").trim().toLowerCase();return state.catalog.find(x=>x.code.toLowerCase()===c);}
function lineTotal(it){let q=Number(it.qty)||0;if(["iverica","medijapan","ploca"].includes(it.cat))q*=1+(Number(state.settings.wastePct)||0)/100;return q*(Number(it.price)||0);}
function initNav(){document.querySelectorAll(".nav-btn").forEach(btn=>{btn.onclick=()=>{document.querySelectorAll(".nav-btn").forEach(b=>b.classList.remove("active"));btn.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));$(`view-${btn.dataset.view}`).classList.remove("hidden");};});}
function renderProjects(){$("projectSelect").innerHTML=state.projects.map(p=>`<option value="${p.id}" ${p.id===state.currentId?"selected":""}>${p.name}</option>`).join("");}
function bindProjectFields(){const p=currentProject();["clientName","clientPhone","clientCity","leadTime"].forEach(id=>{if(!$(id))return;$(id).value=p[id]||(id==="leadTime"?21:"");$(id).oninput=()=>{const pr=currentProject();pr[id]=id==="leadTime"?Number($(id).value):$(id).value;if(id==="clientName"&&$(id).value)pr.name=$(id).value;renderProjects();save();};});}
function renderItems(){const p=currentProject();$("itemsBody").innerHTML=p.items.map(it=>`<tr><td>${catLabel(it.cat)}</td><td><input data-k="code" data-id="${it.id}" value="${it.code||""}"></td><td><input data-k="name" data-id="${it.id}" value="${escapeAttr(it.name)}"></td><td><input data-k="qty" data-id="${it.id}" type="number" step="0.01" value="${it.qty}"></td><td>${unitLabel(it.unit)}</td><td><input data-k="price" data-id="${it.id}" type="number" step="0.01" value="${it.price}"></td><td>${money(lineTotal(it))}</td><td><button class="btn danger" data-del="${it.id}">x</button></td></tr>`).join("")||`<tr><td colspan="8" class="hint">Нема ставки.</td></tr>`;
$("itemsBody").querySelectorAll("input").forEach(inp=>{inp.oninput=()=>{const item=currentProject().items.find(x=>x.id===inp.dataset.id);const k=inp.dataset.k;item[k]=(k==="qty"||k==="price")?Number(inp.value):inp.value;if(k==="code"){const f=findByCode(inp.value);if(f){item.name=f.name;item.cat=f.cat;item.unit=f.unit;item.price=f.price;}}save();renderItems();renderTotals();};});
$("itemsBody").querySelectorAll("[data-del]").forEach(btn=>{btn.onclick=()=>{const pr=currentProject();pr.items=pr.items.filter(x=>x.id!==btn.dataset.del);save();renderItems();renderTotals();};});}
function renderTotals(){const byCat={};let material=0;currentProject().items.forEach(it=>{const t=lineTotal(it);byCat[it.cat]=(byCat[it.cat]||0)+t;material+=t;});const margin=material*(Number(state.settings.marginPct)||0)/100,net=material+margin,vat=net*(Number(state.settings.vatPct)||0)/100;$("totalsBox").innerHTML=Object.entries(byCat).map(([c,v])=>`<div class="tot"><span>${catLabel(c)}</span><span>${money(v)}</span></div>`).join("")+`<div class="tot"><span>Со отпад</span><span>${money(material)}</span></div><div class="tot"><span>Маржа</span><span>${money(margin)}</span></div><div class="tot"><span>Без DDV</span><span>${money(net)}</span></div><div class="tot"><span>DDV</span><span>${money(vat)}</span></div><div class="tot big"><span>За наплата</span><span>${money(net+vat)}</span></div>`;}
function addItem(src,qty){currentProject().items.push({id:uid(),code:src.code||"",name:src.name||"Нова ставка",cat:src.cat||"ostanato",unit:src.unit||"kom",qty:qty??1,price:Number(src.price)||0});save();renderItems();renderTotals();}
function searchCatalog(q){const s=q.trim().toLowerCase();if(!s)return[];return state.catalog.filter(x=>x.code.toLowerCase().includes(s)||x.name.toLowerCase().includes(s)).slice(0,8);}
function setupSearch(){if($("qtyUnit"))fillSelect($("qtyUnit"),UNITS,"kom");const box=$("searchResults");$("searchInput").oninput=()=>{const list=searchCatalog($("searchInput").value);searchSelected=list[0]||null;if(!list.length){box.classList.add("hidden");box.innerHTML="";return;}box.classList.remove("hidden");box.innerHTML=list.map(x=>`<div class="search-item" data-code="${x.code}"><span><b>${x.code}</b> — ${x.name}</span><span>${money(x.price)}</span></div>`).join("");box.querySelectorAll(".search-item").forEach(el=>{el.onclick=()=>{searchSelected=findByCode(el.dataset.code);$("searchInput").value=searchSelected.code+" — "+searchSelected.name;box.classList.add("hidden");};});};
$("addBtn").onclick=()=>{const raw=$("searchInput").value;const code=raw.split("—")[0].trim();const found=findByCode(code)||searchSelected||searchCatalog(raw)[0];if(!found)addItem({name:raw||"Нова ставка",cat:"ostanato",unit:"kom",price:0},Number($("qtyInput").value));else addItem(found,Number($("qtyInput").value));$("searchInput").value="";box.classList.add("hidden");};
if($("addEmptyBtn"))$("addEmptyBtn").onclick=()=>addItem({name:"",cat:"ostanato",unit:"kom",price:0},1);
if($("quickChips")){$("quickChips").innerHTML=[["KL500SC","Клизач"],["SHSC","Клапшарки"],["PVC2","Кант"],["MONT","Монтажа"],["PREVOZ","Превоз"]].map(([c,l])=>`<button class="chip" data-code="${c}">${l}</button>`).join("");$("quickChips").querySelectorAll(".chip").forEach(b=>b.onclick=()=>{const it=findByCode(b.dataset.code);if(it)addItem(it,1);});}}
function renderCatalog(){const q=($("catalogFilter").value||"").toLowerCase();$("catalogBody").innerHTML=state.catalog.filter(x=>!q||x.code.toLowerCase().includes(q)||x.name.toLowerCase().includes(q)).map(x=>`<tr><td>${x.code}</td><td>${x.name}</td><td>${catLabel(x.cat)}</td><td>${unitLabel(x.unit)}</td><td>${Number(x.price).toFixed(2)}</td><td><button class="btn ghost" data-edit="${x.id}">Измени</button> <button class="btn danger" data-cdel="${x.id}">x</button></td></tr>`).join("");
$("catalogBody").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openCatalogModal(b.dataset.edit));
$("catalogBody").querySelectorAll("[data-cdel]").forEach(b=>b.onclick=()=>{state.catalog=state.catalog.filter(x=>x.id!==b.dataset.cdel);save();renderCatalog();});}
function openCatalogModal(id){const item=id?state.catalog.find(x=>x.id===id):{code:"",name:"",cat:"iverica",unit:"tabla",price:0};modalMode=id||"new";$("modalTitle").textContent=id?"Измени":"Нова ставка";$("modalForm").innerHTML=`<label>Шифра<input id="m_code" value="${item.code||""}"></label><label>Име<input id="m_name" value="${escapeAttr(item.name||"")}"></label><label>Категорија<select id="m_cat"></select></label><label>Единица<select id="m_unit"></select></label><label>Цена<input id="m_price" type="number" step="0.01" value="${item.price||0}"></label>`;fillSelect($("m_cat"),CATS,item.cat);fillSelect($("m_unit"),UNITS,item.unit);$("modal").classList.remove("hidden");$("modalSave").onclick=()=>{const payload={code:$("m_code").value.trim(),name:$("m_name").value.trim(),cat:$("m_cat").value,unit:$("m_unit").value,price:Number($("m_price").value)};if(modalMode==="new")state.catalog.push({...payload,id:uid()});else Object.assign(state.catalog.find(x=>x.id===id),payload);save();renderCatalog();$("modal").classList.add("hidden");};}
function guessCatUnit(t){t=(t||"").toLowerCase();if(/kant|pvc|abs|кант/.test(t))return["kant","m"];if(/ивер|iver/.test(t))return["iverica","tabla"];if(/крое|кантир/.test(t))return["trud","tabla"];if(/монт/.test(t))return["montaza","komplet"];if(/превоз/.test(t))return["prevoz","komplet"];return["ostanato","kom"];}
function parsePriceListText(text){const rows=[];String(text||"").split(/\n+/).map(l=>l.replace(/\s+/g," ").trim()).filter(l=>l.length>2).forEach((line,i)=>{const nums=[...line.matchAll(/(\d+[.,]\d+|\d+)/g)].map(m=>m[1]);if(!nums.length)return;const price=Number(nums[nums.length-1].replace(",","."));if(!(price>0))return;const without=line.replace(new RegExp(nums[nums.length-1]+"\\s*(eur|€|ден|mkd)?\\s*$","i"),"").trim();const cm=without.match(/([A-ZА-Ш0-9]{1,6}[-_/]?[A-ZА-Ш0-9]{1,8})/i);let code=cm?cm[1].toUpperCase():("AUTO"+String(i+1).padStart(3,"0"));const [cat,unit]=guessCatUnit(line);rows.push({id:uid(),keep:true,code,name:without||line,cat,unit,price});});return rows;}
function renderOcrRows(){const body=$("ocrBody");if(!body)return;if(!ocrRows.length){body.innerHTML=`<tr><td colspan="6" class="hint">Нема ставки.</td></tr>`;return;}const catOpts=CATS.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");const unitOpts=UNITS.map(([v,l])=>`<option value="${v}">${l}</option>`).join("");body.innerHTML=ocrRows.map(r=>`<tr><td><input type="checkbox" data-keep="${r.id}" checked></td><td><input data-ok="code" data-id="${r.id}" value="${escapeAttr(r.code)}"></td><td><input data-ok="name" data-id="${r.id}" value="${escapeAttr(r.name)}"></td><td><select data-ok="cat" data-id="${r.id}">${catOpts}</select></td><td><select data-ok="unit" data-id="${r.id}">${unitOpts}</select></td><td><input data-ok="price" data-id="${r.id}" type="number" step="0.01" value="${r.price}"></td></tr>`).join("");body.querySelectorAll("select").forEach(sel=>{sel.value=ocrRows.find(x=>x.id===sel.dataset.id)[sel.dataset.ok];});body.querySelectorAll("[data-ok]").forEach(el=>{el.oninput=()=>{ocrRows.find(x=>x.id===el.dataset.id)[el.dataset.ok]=el.dataset.ok==="price"?Number(el.value):el.value;};});body.querySelectorAll("[data-keep]").forEach(el=>{el.onchange=()=>{ocrRows.find(x=>x.id===el.dataset.keep).keep=el.checked;};});}
async function runOcrOnFiles(files){if(!window.Tesseract){$("ocrStatus").textContent="Треба интернет за OCR.";return;}$("ocrStatus").textContent="Читам...";let all="";for(const f of files){const res=await Tesseract.recognize(f,"eng").catch(()=>null);all+=(res&&res.data&&res.data.text?res.data.text:"")+"\n";}$("ocrRaw").value=all.trim();ocrRows=parsePriceListText(all);renderOcrRows();$("ocrStatus").textContent="Најдени "+ocrRows.length+" ставки.";}
function setupImport(){if($("importBtn"))$("importBtn").onclick=()=>{let n=0;$("importText").value.split(/\n+/).forEach(line=>{const p=line.split(/[,;\t]/).map(x=>x.trim());if(p.length<5)return;const [code,name,cat,unit,price]=p;const ex=findByCode(code);const row={code,name,cat,unit,price:Number(price)};if(ex)Object.assign(ex,row);else state.catalog.push({...row,id:uid()});n++;});save();renderCatalog();alert("Увезени "+n);};
if($("exportCsvBtn"))$("exportCsvBtn").onclick=()=>{const csv=state.catalog.map(x=>[x.code,x.name,x.cat,x.unit,x.price].join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="sifarnik.csv";a.click();};
if($("pricePhoto"))$("pricePhoto").onchange=e=>{ocrFiles=[...e.target.files];$("photoPreview").innerHTML=ocrFiles.map(f=>`<img src="${URL.createObjectURL(f)}">`).join("");};
if($("ocrBtn"))$("ocrBtn").onclick=()=>{if(!ocrFiles.length){$("ocrStatus").textContent="Прикачи слика.";return;}runOcrOnFiles(ocrFiles);};
if($("reparseBtn"))$("reparseBtn").onclick=()=>{ocrRows=parsePriceListText($("ocrRaw").value);renderOcrRows();};
if($("saveOcrBtn"))$("saveOcrBtn").onclick=()=>{const vendor=($("vendorName").value||"").trim();const cur=$("vendorCurrency").value;let n=0;ocrRows.filter(r=>r.keep&&r.code&&r.price>0).forEach(r=>{let price=Number(r.price);if(cur==="MKD")price=+(price/61.5).toFixed(2);const name=vendor?r.name+" ("+vendor+")":r.name;const ex=findByCode(r.code);const row={code:r.code,name,cat:r.cat,unit:r.unit,price,vendor};if(ex)Object.assign(ex,row);else state.catalog.push({...row,id:uid()});n++;});save();renderCatalog();alert("Зачувани "+n);};}
function setupSettings(){["wastePct","vatPct","marginPct","defaultTransport","defaultInstall"].forEach(id=>{if(!$(id))return;$(id).value=state.settings[id];$(id).oninput=()=>{state.settings[id]=Number($(id).value);save();renderTotals();};});if($("currency")){$("currency").value=state.settings.currency;$("currency").oninput=()=>{state.settings.currency=$("currency").value;save();renderTotals();renderItems();};}}
function addSilent(project,code,qty){const src=findByCode(code);if(!src)return;project.items.push({id:uid(),...src,qty});}
function setupChrome(){$("projectSelect").onchange=()=>{state.currentId=$("projectSelect").value;save();bindProjectFields();renderItems();renderTotals();};
$("newProjectBtn").onclick=()=>{const p={id:uid(),name:"Понуда "+(state.projects.length+1),clientName:"",clientPhone:"",clientCity:"",leadTime:21,items:[]};addSilent(p,"PREVOZ",1);addSilent(p,"MONT",1);state.projects.push(p);state.currentId=p.id;save();renderProjects();bindProjectFields();renderItems();renderTotals();};
$("printBtn").onclick=()=>window.print();if($("catalogFilter"))$("catalogFilter").oninput=renderCatalog;if($("addCatalogBtn"))$("addCatalogBtn").onclick=()=>openCatalogModal(null);if($("modalCancel"))$("modalCancel").onclick=()=>$("modal").classList.add("hidden");}
function init(){initNav();setupChrome();setupSearch();setupImport();setupSettings();renderProjects();bindProjectFields();renderItems();renderTotals();renderCatalog();}
init();
