const CATS=[["iverica","Иверка"],["medijapan","Медијапан"],["kant_pvc","Кант PVC"],["kant_abs1","ABS 1мм"],["kant_abs2","ABS 2мм"],["klizac","Клизачи"],["sarka","Клапшарки"],["drugo","Друго"]];
const UNITS=[["tabla","табла"],["m","м"],["kom","ком"],["komplet","комплет"]];
const DEFAULT_PRICES=[{code:"PVC22",name:"PVC кант 04/22",cat:"kant_pvc",unit:"m",price:0.41},{code:"ABS22",name:"ABS 08/22 1мм",cat:"kant_abs1",unit:"m",price:0.78},{code:"ABS28",name:"ABS 08/28 2мм",cat:"kant_abs2",unit:"m",price:1.06},{code:"ABS41",name:"ABS 08/41 2мм",cat:"kant_abs2",unit:"m",price:1.63},{code:"KL500",name:"Клизач 500 soft-close",cat:"klizac",unit:"kom",price:9.8},{code:"SHSC",name:"Клапшарка soft-close",cat:"sarka",unit:"kom",price:1.9},{code:"RACKA",name:"Рачка",cat:"drugo",unit:"kom",price:2.5},{code:"PREVOZ",name:"Превоз",cat:"drugo",unit:"komplet",price:25},{code:"MONT",name:"Монтажа",cat:"drugo",unit:"komplet",price:60}];
const $=id=>document.getElementById(id);
const uid=()=>Math.random().toString(36).slice(2,9);
const catLabel=v=>(CATS.find(c=>c[0]===v)||[v,v])[1];
const unitLabel=v=>(UNITS.find(c=>c[0]===v)||[v,v])[1];
const money=n=>`${(Number(n)||0).toFixed(2)} €`;
const norm=s=>String(s||"").toUpperCase().replace(/\s+/g,"");
function blankProject(id){return{id,created:Date.now(),clientName:"",clientPhone:"",clientCity:"",clientNote:"",items:[]};}
function load(){try{const raw=localStorage.getItem("mebel-v2");if(raw)return JSON.parse(raw);}catch(e){}const id=uid();return{prices:DEFAULT_PRICES.map(x=>({...x,id:uid()})),projects:[blankProject(id)],currentId:id,priceTab:"iverica"};}
let state=load(),extraBoards=0,editingPrice=null;
const save=()=>localStorage.setItem("mebel-v2",JSON.stringify(state));
const current=()=>state.projects.find(p=>p.id===state.currentId)||state.projects[0];
function lineTotal(it){let q=Number(it.qty)||0;if(it.cat==="iverica"||it.cat==="medijapan")q*=1.12;return q*(Number(it.price)||0);}
function projectTotal(p){return(p.items||[]).reduce((s,it)=>s+lineTotal(it),0);}
function brioVars(code){if(!window.BRIO)return[];const c=norm(code);return BRIO.boards.filter(g=>String(g.codes).split(",").map(norm).includes(c));}
function show(view){document.querySelectorAll(".view").forEach(v=>v.classList.add("hidden"));document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.view===view));$(`view-${view}`).classList.remove("hidden");if(view==="prices")renderPrices();if(view==="projects")renderProjects();if(view==="new")renderProject();}
function startNew(){const p=blankProject(uid());state.projects.unshift(p);state.currentId=p.id;extraBoards=0;save();show("new");}
function bindClient(){const p=current();["clientName","clientPhone","clientCity","clientNote"].forEach(k=>{const el=$(k);if(!el)return;el.value=p[k]||"";el.oninput=()=>{current()[k]=el.value;$("projLabel").textContent=current().clientName||"Клиент, па материјал";save();};});$("projLabel").textContent=p.clientName||"Клиент, па материјал";}
function renderBoards(){const box=$("boardRows");if(!box)return;const rows=current().items.filter(x=>x.cat==="iverica"||x.cat==="medijapan");const slots=Math.max(rows.length+extraBoards,1);let html="";for(let i=0;i<slots;i++){const it=rows[i];const code=it?it.code:"";const vars=brioVars(code);const opts=`<option value="">дебелина</option>`+vars.map((g,j)=>{const sel=it&&Number(it.price)===g.price&&it.thick===g.thick?" selected":"";return `<option value="${j}"${sel}>${g.thick} ${g.finish} · ${g.price}€</option>`;}).join("");html+=`<div class="board-row"><input data-bc="${i}" placeholder="D123" value="${code||""}"><select data-bv="${i}">${opts}</select><input data-bq="${i}" type="number" min="0.5" step="0.5" value="${it?it.qty:1}"><span class="price-hint">${it?money(lineTotal(it)):"табли"}</span><button class="btn danger" type="button" data-bd="${i}">x</button></div>`;}box.innerHTML=html;
box.querySelectorAll("[data-bc]").forEach(inp=>{inp.onchange=()=>{const i=Number(inp.dataset.bc);const code=norm(inp.value);const vars=brioVars(code);const qty=Number(box.querySelector(`[data-bq="${i}"]`).value)||1;const g=vars[0];if(rows[i]){rows[i].code=code;if(g)Object.assign(rows[i],{name:`${g.name} ${code} ${g.thick}`,price:g.price,thick:g.thick,unit:"tabla"});save();}else if(g){extraBoards=Math.max(0,extraBoards-1);addItem({code,name:`${g.name} ${code} ${g.thick}`,cat:"iverica",unit:"tabla",price:g.price,thick:g.thick},qty);return;}else{extraBoards=Math.max(0,extraBoards-1);addItem({code,name:code||"Плоча",cat:"iverica",unit:"tabla",price:0},qty);return;}renderProject();};});
box.querySelectorAll("[data-bv]").forEach(sel=>{sel.onchange=()=>{const i=Number(sel.dataset.bv);const code=norm(box.querySelector(`[data-bc="${i}"]`).value);const g=brioVars(code)[Number(sel.value)];if(!g||!rows[i])return;Object.assign(rows[i],{code,name:`${g.name} ${code} ${g.thick}`,price:g.price,thick:g.thick});save();renderProject();};});
box.querySelectorAll("[data-bq]").forEach(inp=>{inp.oninput=()=>{const i=Number(inp.dataset.bq);if(rows[i]){rows[i].qty=Number(inp.value)||0;save();renderTotals();}};});
box.querySelectorAll("[data-bd]").forEach(btn=>{btn.onclick=()=>{const i=Number(btn.dataset.bd);if(rows[i])current().items=current().items.filter(x=>x.id!==rows[i].id);else extraBoards=Math.max(0,extraBoards-1);save();renderProject();};});}
function renderGroup(boxId,cats){const box=$(boxId);const rows=current().items.filter(x=>cats.includes(x.cat));if(!rows.length){box.innerHTML=`<p class="hint">Празно. Додај од копчето горе.</p>`;return;}box.innerHTML=rows.map(it=>`<div class="line-row"><div><b>${it.name}</b><div class="hint">${catLabel(it.cat)} · ${it.code||""}</div></div><input data-q="${it.id}" type="number" step="0.01" value="${it.qty}"><div>${money(it.price)} / ${unitLabel(it.unit)}</div><div>${money(lineTotal(it))}</div><button class="btn danger" data-x="${it.id}" type="button">x</button></div>`).join("");
box.querySelectorAll("[data-q]").forEach(inp=>{inp.oninput=()=>{const it=current().items.find(x=>x.id===inp.dataset.q);it.qty=Number(inp.value)||0;save();renderTotals();};});
box.querySelectorAll("[data-x]").forEach(btn=>{btn.onclick=()=>{current().items=current().items.filter(x=>x.id!==btn.dataset.x);save();renderProject();};});}
function renderTotals(){const p=current();const groups={};p.items.forEach(it=>{groups[it.cat]=(groups[it.cat]||0)+lineTotal(it);});const sum=projectTotal(p);$("totalsBox").innerHTML=Object.entries(groups).map(([c,v])=>`<div class="tot"><span>${catLabel(c)}</span><span>${money(v)}</span></div>`).join("")+`<div class="tot big"><span>Вкупно</span><span>${money(sum)}</span></div>`;}
function addItem(src,qty){current().items.push({id:uid(),code:src.code||"",name:src.name||"",cat:src.cat||"drugo",unit:src.unit||"kom",qty:qty??1,price:Number(src.price)||0,thick:src.thick||""});save();renderProject();}
function pickFromCatalog(cat){const list=state.prices.filter(x=>x.cat===cat);if(!list.length){openPriceModal(null,cat);return;}$("modalTitle").textContent="Одбери од ценовник";$("modalForm").innerHTML=list.map(x=>`<button class="btn ghost" type="button" data-pick="${x.id}">${x.name} — ${money(x.price)} / ${unitLabel(x.unit)}</button>`).join("");$("modal").classList.remove("hidden");$("modalSave").style.display="none";$("modalForm").querySelectorAll("[data-pick]").forEach(b=>{b.onclick=()=>{const src=state.prices.find(x=>x.id===b.dataset.pick);$("modal").classList.add("hidden");$("modalSave").style.display="";addItem(src,1);};});}
function renderPrices(){const tab=state.priceTab||"iverica";$("priceTabs").innerHTML=CATS.map(([v,l])=>`<button class="tab ${v===tab?"active":""}" data-tab="${v}">${l}</button>`).join("");$("priceTabs").querySelectorAll("[data-tab]").forEach(b=>{b.onclick=()=>{state.priceTab=b.dataset.tab;save();renderPrices();};});const rows=state.prices.filter(x=>x.cat===tab);$("priceBody").innerHTML=rows.map(x=>`<tr><td>${x.code}</td><td>${x.name}</td><td>${unitLabel(x.unit)}</td><td>${Number(x.price).toFixed(2)}</td><td><button class="btn ghost" data-edit="${x.id}">Измени</button> <button class="btn" data-ok="${x.id}">Зачувај</button> <button class="btn danger" data-del="${x.id}">Избриши</button></td></tr>`).join("")||`<tr><td colspan="5" class="hint">Нема ставки.</td></tr>`;
$("priceBody").querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>openPriceModal(b.dataset.edit));
$("priceBody").querySelectorAll("[data-ok]").forEach(b=>b.onclick=()=>alert("Зачувано."));
$("priceBody").querySelectorAll("[data-del]").forEach(b=>{b.onclick=()=>{if(!confirm("Избриши?"))return;state.prices=state.prices.filter(x=>x.id!==b.dataset.del);save();renderPrices();};});}
function openPriceModal(id,forcedCat){const item=id?state.prices.find(x=>x.id===id):{code:"",name:"",cat:forcedCat||state.priceTab||"drugo",unit:"kom",price:0};editingPrice=id||"new";$("modalTitle").textContent=id?"Измени":"Нова ставка";$("modalSave").style.display="";$("modalForm").innerHTML=`<label>Шифра<input id="m_code" value="${item.code||""}"></label><label>Име<input id="m_name" value="${item.name||""}"></label><label>Група<select id="m_cat">${CATS.map(([v,l])=>`<option value="${v}" ${v===item.cat?"selected":""}>${l}</option>`).join("")}</select></label><label>Единица<select id="m_unit">${UNITS.map(([v,l])=>`<option value="${v}" ${v===item.unit?"selected":""}>${l}</option>`).join("")}</select></label><label>Цена €<input id="m_price" type="number" step="0.01" value="${item.price||0}"></label>`;$("modal").classList.remove("hidden");}
function savePrice(){const row={code:$("m_code").value.trim(),name:$("m_name").value.trim(),cat:$("m_cat").value,unit:$("m_unit").value,price:Number($("m_price").value)||0};if(editingPrice==="new")state.prices.push({...row,id:uid()});else Object.assign(state.prices.find(x=>x.id===editingPrice),row);save();$("modal").classList.add("hidden");renderPrices();}
function renderProjects(){const list=$("projectList");const items=state.projects.slice().sort((a,b)=>(b.created||0)-(a.created||0));list.innerHTML=items.map(p=>`<div class="card proj-card"><div><h3>${p.clientName||"Без име"}</h3><div class="hint">${p.clientPhone||""} · ${p.clientCity||""} · ${money(projectTotal(p))}</div><div class="hint">${p.clientNote||""}</div></div><div class="row"><button class="btn" data-open="${p.id}">Отвори</button><button class="btn danger" data-pdel="${p.id}">Избриши</button></div></div>`).join("")||`<div class="card hint">Нема проекти.</div>`;
list.querySelectorAll("[data-open]").forEach(b=>{b.onclick=()=>{state.currentId=b.dataset.open;extraBoards=0;save();show("new");};});
list.querySelectorAll("[data-pdel]").forEach(b=>{b.onclick=()=>{if(!confirm("Избриши проект?"))return;state.projects=state.projects.filter(x=>x.id!==b.dataset.pdel);if(!state.projects.length){const p=blankProject(uid());state.projects=[p];state.currentId=p.id;}else if(state.currentId===b.dataset.pdel)state.currentId=state.projects[0].id;save();renderProjects();};});}
function renderProject(){bindClient();renderBoards();renderGroup("kantRows",["kant_pvc","kant_abs1","kant_abs2"]);renderGroup("okovRows",["klizac","sarka","drugo"]);renderTotals();}
function init(){document.querySelectorAll(".nav-btn").forEach(b=>{b.onclick=()=>{if(b.dataset.view==="new"){const p=current();if(p.clientName||p.clientPhone||(p.items&&p.items.length))startNew();else show("new");}else show(b.dataset.view);};});
$("addBoardBtn").onclick=()=>{extraBoards+=1;renderBoards();};
document.querySelectorAll("[data-addcat]").forEach(b=>{b.onclick=()=>pickFromCatalog(b.dataset.addcat);});
$("addPriceBtn").onclick=()=>openPriceModal(null);
$("modalCancel").onclick=()=>{$("modal").classList.add("hidden");$("modalSave").style.display="";};
$("modalSave").onclick=savePrice;
$("printBtn").onclick=()=>window.print();
$("newFromListBtn").onclick=startNew;
renderProject();}
init();
